global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'task-tracker-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task-tracker-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'task-tracker-app'

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'task-tracker-db'

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
